### PR TITLE
Completed modifying CSS code to make it mobile-first and fully responsive

### PR DESCRIPTION
**Pull request by BohdiCave**
This is the finished basic structure that is unlikely to change whatever we do with the APIs. Tweaks will be necessary, but this should be the final base draft of the page, so let's merge it with the main branch.

### CODE REVIEW

**Comment by dfischer4623** [comment]
Looks fine to me.

**Comment by dfischer4623** [comment]
I like what you have done.  Let me know when you have merged into main.  I will then pull and put my code into articles.

**Comment by BohdiCave** [comment]
> I like what you have done. Let me know when you have merged into main. I will then pull and put my code into articles.

David, for these changes to merge into the main, one of you needs to approve it. You, Logan or Dereck have to review and sign off on it. I cannot make any changes to the main on my own and neither can any of you - that was why we were asked to turn on protection for the main branch. 

There's not hurry here, we can do this tomorrow during class, if it's not done sooner. I wanted to do it sooner rather than later, to allow all of you to use the same basis for coding your parts. I might do some more work on it tomorrow before class, if I have a chance, to add more form functionality. Doing our latest homework has been helpful to figure out various form-related quirks.

**Review by dfischer4623 — APPROVED** [review]

**Comment by dfischer4623** [comment]
Sorry, I thought I had approved a couple days ago.

**Comment by BohdiCave** [comment]
No worries, we’re all getting used to it all. This was a second update I
did, maybe you thought it was already approved. Thanks!

вт, 6 жовт. 2020 о 9:50 дп David Fischer <notifications@github.com> пише:

**Pull request merged**
